ps/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts
  get 'ps3/index'
  resources :quotations

  get 'main/index'

  get 'ps1/index'
  get 'ps1/dzero'
  get 'ps1/gnews'

  get 'ps2/index'
  get 'ps2/quotations'
  post 'ps2/set_cookies'
  get 'ps2/delete_cookies'
  get 'ps2/import'
  get 'ps2/export'
  get 'ps2/savexml'
  post 'ps2/importquote'
  get 'posts/index'
  get 'ps3/showpdf'
  post 'posts/banuser'
  root 'main#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

ps/app/models/quotation.rb
class Quotation < ApplicationRecord
  attr_accessor :category_new
  #validates_uniqueness_of :category
  #validates :category1, presence: true, if: -> { !category1.present? }
  #validates :category, uniqueness: { scope: :category1 }
  validates :author_name, presence: true
  validates :quote, presence: true

  def show

  end

  def Quotation.groups
    #return Quotation.find(:all, :select => "DISTINCT category")
    return find_by_sql("SELECT DISTINCT category from quotations; ")
  end

end

ps/app/controllers/quotations_controller.rb
class QuotationsController < ApplicationController
  before_action :set_quotation, only: [:show, :edit, :update, :destroy]

  # GET /quotations
  # GET /quotations.json
  def index
    @quotations = Quotation.all
    @category_quote = Quotation.all.pluck(:category)
  end

  # GET /quotations/1
  # GET /quotations/1.json
  def show
  end

  # GET /quotations/new
  def new
    @quotation = Quotation.new
  end

  # GET /quotations/1/edit
  def edit
  end

  # POST /quotations
  # POST /quotations.json
  def create
    #puts quotation_params
    temp = quotation_params

    if !temp[:category_new].empty?
      temp[:category] = temp[:category_new]
    end

#=begin
    @quotation = Quotation.new(temp)

    respond_to do |format|
      if @quotation.save
        format.html { redirect_to ps2_quotations_path, notice: 'Quotation was successfully created.' }
        format.json { render :show, status: :created, location: ps2_quotations_path}
      else
        format.html { render :new }
        format.json { render json: @quotation.errors, status: :unprocessable_entity }
      end
    end
    #=end

  end

  # PATCH/PUT /quotations/1
  # PATCH/PUT /quotations/1.json
  def update
    respond_to do |format|
      if @quotation.update(quotation_params)
        format.html { redirect_to @quotation, notice: 'Quotation was successfully updated.' }
        format.json { render :show, status: :ok, location: @quotation }
      else
        format.html { render :edit }
        format.json { render json: @quotation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotations/1
  # DELETE /quotations/1.json
  def destroy
    @quotation.destroy
    respond_to do |format|
      format.html { redirect_to quotations_url, notice: 'Quotation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end



  private
  # Use callbacks to share common setup or constraints between actions.
  def set_quotation
    @quotation = Quotation.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def quotation_params
    params.require(:quotation).permit(:author_name, :category, :quote,:category_new)
  end
end

ps/app/helpers/quotations_helper.rb
module QuotationsHelper
end

ps/app/views/quotations/_form.html.erb
<%= form_with(model: quotation, local: true) do |form| %>
  <% if quotation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(quotation.errors.count, "error") %> prohibited this quotation from being saved:</h2>

      <ul>
        <% quotation.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :author_name %>
    <%= form.text_field :author_name %>
  </div>



  <div class="field">
    <%= form.label :category_new %>
    <%= form.text_field :category_new %>

  </div>

  <div class="field">
    <%= form.collection_select :category, Quotation.groups ,:category, :category %>
  </div>



  <div class="field">
    <%= form.label :quote %>
    <%= form.text_area :quote %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

ps/app/views/quotations/edit.html.erb
<h1>Editing Quotation</h1>

<%= render 'form', quotation: @quotation %>

<%= link_to 'Show', @quotation %> |
<%= link_to 'Back', quotations_path %>

ps/app/views/quotations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Quotations</h1>

<table>
  <thead>
  <tr>
    <th>Author name</th>
    <th>Category</th>
    <th>Quote</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @quotations.each do |quotation| %>
    <tr>
      <td><%= quotation.author_name %></td>
      <td><%= quotation.category %></td>
      <td><%= quotation.quote %></td>
      <td><%= link_to 'Show', quotation %></td>
      <td><%= link_to 'Edit', edit_quotation_path(quotation) %></td>
      <td><%= link_to 'Destroy', quotation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Quotation', new_quotation_path %>

ps/app/views/quotations/new.html.erb
<h1>New Quotation</h1>

<%= render 'form', quotation: @quotation %>

<%= link_to 'Back', quotations_path %>

ps/app/views/quotations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Author name:</strong>
  <%= @quotation.author_name %>
</p>

<p>
  <strong>Category:</strong>
  <%= @quotation.category %>
</p>

<p>
  <strong>Quote:</strong>
  <%= @quotation.quote %>
</p>

<%= link_to 'Edit', edit_quotation_path(@quotation) %> |
<%= link_to 'Back', quotations_path %>