ps/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts
  get 'ps3/index'
  resources :quotations

  get 'main/index'

  get 'ps1/index'
  get 'ps1/dzero'
  get 'ps1/gnews'

  get 'ps2/index'
  get 'ps2/quotations'
  post 'ps2/set_cookies'
  get 'ps2/delete_cookies'
  get 'ps2/import'
  get 'ps2/export'
  get 'ps2/savexml'
  post 'ps2/importquote'
  get 'posts/index'
  get 'ps3/showpdf'
  post 'posts/banuser'
  root 'main#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

ps/app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

end

ps/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
    @users = User.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
    @post.user = current_user
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html {redirect_to @post, notice: 'Post was successfully created.'}
        format.json {render :show, status: :created, location: @post}
      else
        format.html {render :new}
        format.json {render json: @post.errors, status: :unprocessable_entity}
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    @post.user = current_user
    respond_to do |format|
      if @post.update(post_params)
        format.html {redirect_to @post, notice: 'Post was successfully updated.'}
        format.json {render :show, status: :ok, location: @post}
      else
        format.html {render :edit}
        format.json {render json: @post.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html {redirect_to posts_url, notice: 'Post was successfully destroyed.'}
      format.json {head :no_content}
    end
  end

  def delete
    redirect_to new_user_session_path
  end

  # def banuser
  #   current_user.banstatus = "true"
  #   redirect_to posts_url
  # end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def post_params
    params.require(:post).permit(:posttext)
  end
end

ps/app/helpers/posts_helper.rb
module PostsHelper
end

ps/app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :posttext %>
    <%= form.text_area :posttext %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

ps/app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

ps/app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>
<%= link_to "Sign out", destroy_user_session_path, method: :delete %>

<h1>Posts</h1>


<table>
  <thead>
  <tr>
    <th>Posttext</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @posts.each do |post| %>
    <tr>
      <td><%= post.posttext %></td>
      <td><%= link_to 'Show', post %></td>
      <td><%= link_to 'Edit', edit_post_path(post) %></td>
      <td><%= link_to 'Destroy', post, method: :delete, data: {confirm: 'Are you sure?'} %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

<br>
<% if current_user.role.name == "Admin" %>
  <% if current_user.banstatus == "false" %>
    <h1>Users</h1>


    <table>
      <thead>
      <tr>
        <th>Email</th>
        <th colspan="3"></th>
        <th>Name</th>
        <th colspan="3"></th>
        <th>Role</th>
      </tr>
      </thead>

      <tbody>
      <% @users.each do |post| %>
        <tr>
          <td><%= post.email %></td>
          <td colspan="3"></td>
          <td><%= post.name %></td>
          <td colspan="3"></td>

          <td><%= post.role.name %></td>
          <!--      <td><%#= link_to 'Edit', edit_post_path(post) %></td>-->
<!--          <td><%#= link_to 'Ban', posts_banuser_path %></td>-->
        </tr>
      <% end %>
      </tbody>
    </table>
  <% end %>
<% end %>

ps/app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

ps/app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Posttext:</strong>
  <%= @post.posttext %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>