web9project/config/routes.rb
Rails.application.routes.draw do
  resources :comments
  get 'admin/index'
  resources :posts
  devise_for :users
  root 'posts#index'
  get 'admin/ban'
  get 'admin/approve'
  get 'admin/unban'
  get 'admin/deletepost'
  resources :posts do
    resources :comments
  end

  mount SimpleDiscussion::Engine => "/forum"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

web9project/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

web9project/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

web9project/app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy

  has_attached_file :image, styles: { large: "600X600>", medium: "300X300>", thumb:"64X64#"}
  validates_attachment_content_type :image, content_type: /\image\/.*\Z/
end

web9project/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_attached_file :image, styles: { large: "600X600>", medium: "300X300>", thumb:"64X64#"}
  validates_attachment_content_type :image, content_type: /\image\/.*\Z/


  include SimpleDiscussion::ForumUser

  # def name
  #   "#{first_name} #{last_name}"
  # end

end

web9project/app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
    # getting all user list
    @users = User.all
    @count = @users.where('isbanned = :yes',
                          :yes => true,
    ).count
    # getting number of user registered last month
    @lastthirtydays = User.where(
        'created_at >= :thirty_days_ago',
        :thirty_days_ago => 30.days.ago,
    ).count
    @post = Post.all

  end

  def ban
    # MyModel.where(id: 1).update_all(banned: true)
    @id = params[:userid]
    User.where(:id => @id).update_all(:isbanned => true)
    respond_to do |format|
      format.html {redirect_to admin_index_path}
    end
  end

  def unban
    # MyModel.where(id: 1).update_all(banned: true)
    @id = params[:userid]
    User.where(:id => @id).update_all(:isbanned => false)
    respond_to do |format|
      format.html {redirect_to admin_index_path}
    end
  end

  def approve
    @postid = params[:postid]
    Post.where(:id => @postid).update_all(:isapproved => true)
    respond_to do |format|
      format.html {redirect_to admin_index_path}
    end
  end

  def deletepost
    @postid = params[:postid]
    Post.where(:id => @postid).delete_all
    respond_to do |format|
      format.html {redirect_to admin_index_path}
    end
  end

end

web9project/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :update_sanitized_params, if: :devise_controller?

  def update_sanitized_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :address, :phone, :sex, :occupation, :dob, :maritalstatus, :email, :password, :annualincome, :username, :image])
  end
end

web9project/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
    @postid = params[:post_id]
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    @postid = params[:post_id]
  end

  # GET /comments/new
  def new
    @comment = Comment.new
    @postid = params[:post_id]
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)
    @postid=params[:post_id]
    respond_to do |format|
      if @comment.save
        format.html { redirect_to root_path, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    @postid=params[:post_id]
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to root_path, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:commenttext, :post_id, :user_id)
    end
end

web9project/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /posts
  # GET /posts.json
  def index
    @posts = (params[:post].blank?) ? Post.all : Post.where(id: params[:post].split(","))
    @posts = Post.paginate(per_page: 5, page: params[:page])
    @user = current_user
    @comment = Comment.all
    respond_to do |format|
      format.html
      format.json {
        render json: Post.where('title ilike ?', "%#{params[:q]}%")
                         .select('id, title as name')
      }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html {redirect_to @post, notice: 'Post was successfully created, but needs approval from administrator.'}
        # format.html {redirect_to root_url, notice: 'Post was successfully created.'}
        format.json {render :show, status: :created, location: @post}
      else
        format.html {render :new}
        format.json {render json: @post.errors, status: :unprocessable_entity}
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html {redirect_to @post, notice: 'Post was successfully updated.'}
        format.json {render :show, status: :ok, location: @post}
      else
        format.html {render :edit}
        format.json {render json: @post.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html {redirect_to posts_url, notice: 'Post was successfully destroyed.'}
      format.json {head :no_content}
    end

  end


  private


  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def post_params
    params.require(:post).permit(:title, :description, :address, :cost, :email, :latitude, :longitude, :contactname, :apartmentorroom, :numberofroom, :phone, :user_id, :image)
  end
end

web9project/app/helpers/admin_helper.rb
module AdminHelper
end

web9project/app/helpers/application_helper.rb
module ApplicationHelper
  def gender_lists
    I18n.t(:gender_lists).map { |key, value| [ value, key ] }
  end
  def marital_status
    I18n.t(:marital_status).map { |key, value| [ value, key ] }
  end
  def categories
    I18n.t(:categories).map { |key, value| [ value, key ] }
  end

end

web9project/app/helpers/comments_helper.rb
module CommentsHelper
end

web9project/app/helpers/posts_helper.rb
module PostsHelper
end

web9project/app/views/admin/index.html.erb
<h1>Admin DashBoard</h1>


<h2>All Users list</h2>

<table>
  <thead>
  <tr>
    <th>Username</th>
    <th colspan="3"></th>
    <th>Name</th>
    <th colspan="3"></th>
    <th>Email</th>
    <th colspan="3"></th>
    <th>IsAdmin</th>
    <th colspan="3"></th>
    <th>IsBanned</th>
  </tr>
  </thead>

  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.username %></td>
      <td colspan="3"></td>
      <td><%= user.name %></td>
      <td colspan="3"></td>
      <td><%= user.email %></td>
      <td colspan="3"></td>
      <td><%= user.isadmin %></td>
      <td colspan="3"></td>
      <td><%= user.isbanned %></td>

      <% if user.isbanned == false %>
        <% if user.id != current_user.id %>
          <td colspan="3"></td>
          <td><%= link_to 'Ban User', admin_ban_path(userid: user.id) %></td>
        <% end %>
      <% else %>
        <td colspan="3"></td>
        <td><%= link_to 'Unban User', admin_unban_path(userid: user.id) %></td>
      <% end %>
    </tr>
  <% end %>
  </tbody>
</table>

<br><br><br>
<h2>User Statistics</h2>
<ul>
  <li><h4>Number of User registered this month : <%= @lastthirtydays %></h4></li>
  <li><h4>Number of banned user : <%= @count %></h4></li>
</ul>

<br>

<h2>Approval waiting posts</h2>
<table>
  <thead>
  <tr>
    <th>Title</th>
    <th colspan="3"></th>
    <th>IsApproved</th>
  </tr>
  </thead>

  <tbody>
  <% @post.each do |post| %>
    <% if post.isapproved == false %>
      <tr>
        <td><%= post.title %></td>
        <td colspan="3"></td>
        <td><%= post.isapproved %></td>
        <td colspan="3"></td>
        <td><%= link_to 'Approve post', admin_approve_path(postid: post.id) %></td>
        <td colspan="3"></td>
        <td><%= link_to 'Reject post', admin_deletepost_path(postid: post.id) %></td>
      </tr>
    <% end %>
  <% end %>
  </tbody>
</table>

<br>

<h2>View all posts</h2>
<table>
  <thead>
  <tr>
    <th>Title</th>
    <td colspan="3"></td>
    <th>Address</th>
    <td colspan="3"></td>
    <th>Cost</th>
  </tr>
  </thead>

  <tbody>
  <% @post.each do |post| %>
    <tr>
      <td><%= post.title %></td>
      <td colspan="3"></td>
      <td><%= post.address %></td>
      <td colspan="3"></td>
      <td><%= post.cost %></td>
      <td colspan="3"></td>

      <td><%= link_to 'Show', post %></td>
      <td colspan="3"></td>
      <td><%= link_to 'Edit', edit_post_path(post) %></td>
      <!--      <td><%#= link_to 'Destroy', post,  :controller => "post", :action => 'destroy', :id => post.id, :confirm => "Are you sure you want to delete", :method => :delete %></td>-->
    </tr>

  <% end %>
  </tbody>
</table>

web9project/app/views/comments/_form.html.erb
<%= form_with(model: comment, local: true) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :commenttext %>
    <%= form.text_field :commenttext %>
  </div>


  <div class="field">
    postid<%= @postid %>
    <%= form.hidden_field :post_id, value: @postid %>

  </div>
  <div class="field">
    Userid<%= current_user.id %>
    <%= form.hidden_field :user_id, value: current_user.id %>

  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

web9project/app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

web9project/app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Commenttext</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.commenttext %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

web9project/app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

web9project/app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Commenttext:</strong>
  <%= @comment.commenttext %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

web9project/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Web9project</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<% if flash[:error] %>
  <div id="error">
    <%= flash[:error] %>
  </div>
<% end %>
<div id="container">
  <%= link_to "Forum", simple_discussion_path %>
  <div id="user_status">
    <% if user_signed_in? %>

      <% if current_user.isbanned == true %>
        <p>You are banned. Please contact administrator</p>
        <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
      <% else %>
        Welcome <%= current_user.email %>! Not you?
        <%= link_to "Sign out", destroy_user_session_path, method: :delete %>

        <%= image_tag current_user.image.url(:thumb) %>
      <% end %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path %> or
      <%= link_to "Sign in", new_user_session_path %>.
    <% end %>
  </div>
  <%= yield %>
</div>
</body>
</html>

web9project/app/views/posts/_form.html.erb
<%= form_with(model: post, local: true, id: "new_post") do |form| %>
  <%# if post.errors.any? %>
  <!--    <div id="error_explanation">-->
  <!--      <h2><%#= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>-->

  <!--      <ul>-->
  <%# post.errors.full_messages.each do |message| %>
  <!--          <li><%#= message %></li>-->
  <%# end %>
  <!--      </ul>-->
  <!--    </div>-->
  <%# end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :cost %>
    <%= form.text_field :cost %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :latitude %>
    <%= form.text_field :latitude %>
  </div>

  <div class="field">
    <%= form.label :longitude %>
    <%= form.text_field :longitude %>
  </div>

  <div class="field">
    <%= form.label :contactname %>
    <%= form.text_field :contactname %>
  </div>

  <div class="field">
    <%= form.label :apartmentorroom %>
    <%#= form.text_field :apartmentorroom %>
    <%= form.select :apartmentorroom, categories %>
  </div>

  <div class="field">
    <%= form.label :numberofroom %>
    <%= form.number_field :numberofroom %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>
  <div class="field">
<!--    Userid<%#= current_user.id %>-->
    <%= form.hidden_field :user_id, value: current_user.id %>
    <div class="field">
      <%= form.label :image %><br/>
      <%= form.file_field :image %>
    </div>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

web9project/app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

web9project/app/views/posts/index.html.erb
<% if @user.isbanned == false %>
  <p id="notice"><%= notice %></p>
  <% if current_user.isadmin == true %>
    <% controller.redirect_to admin_index_path %>
  <% else %>

    <h1>Posts</h1>
    <div class="post">
    <table>
      <thead>
      <tr>
        <th>Image</th>
        <th colspan="3"></th>
        <th>Title</th>
        <th colspan="3"></th>
        <th>Address</th>
        <th colspan="3"></th>
        <th>Cost</th>
        <th colspan="3"></th>
      </tr>
      </thead>

      <tbody>
      <% @posts.each do |post| %>
        <% if post.isapproved == true %>
          <tr>
            <td><%= image_tag post.image.url(:thumb) %></td>
            <th colspan="3"></th>
            <td><%= post.title %></td>
            <th colspan="3"></th>
            <td><%= post.address %></td>
            <th colspan="3"></th>
            <td><%= post.cost %></td>
            <th colspan="3"></th>
            <td><%= link_to 'Show', post %></td>
            <% if current_user.id == post.user_id %>
              <td><%= link_to 'Edit', edit_post_path(post) %></td>
              <th colspan="3"></th>
              <td><%= link_to 'Destroy', post, method: :delete, data: {confirm: 'Are you sure?'} %></td>
              <th colspan="3"></th>
            <% end %>
          </tr>
        <% end %>
      <% end %>
      </tbody>

    </table>

    </div>
    <%= will_paginate @posts %>
    <br>

    <%= link_to 'New Post', new_post_path %>
  <% end %>
<% else %>
<% end %>

<%= form_tag posts_path, method: "get" do %>
  <%= label_tag(:post, "Search: ") %>
  <%= text_field_tag(:post) %>
  <%= submit_tag("Search") %>
<% end %>

web9project/app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

web9project/app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @post.description %>
</p>

<p>
  <strong>Address:</strong>
  <%= @post.address %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @post.cost %>
</p>

<p>
  <strong>Email:</strong>
  <%= @post.email %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @post.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @post.longitude %>
</p>

<p>
  <strong>Contactname:</strong>
  <%= @post.contactname %>
</p>

<p>
  <strong>Apartmentorroom:</strong>
  <%= @post.apartmentorroom %>
</p>

<p>
  <strong>Numberofroom:</strong>
  <%= @post.numberofroom %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @post.phone %>
</p>
<%# if @post.user_id == @user.id %>
<%#= link_to 'Edit', edit_post_path(@post) %>
<!--  <br>-->
<%# end %>
<%#= link_to 'Back', posts_path %>

<h3>Comments</h3>
<table>
  <thead>
  <tr>
    <th>Name</th>
    <th>Comment</th>
  </thead>
  <tbody>
  <% @post.comments.each do |comments| %>
    <tr>
      <td><%= comments.user_id %></td>
      <td><%= comments.commenttext %></td>
      <% if current_user.id == comments.user_id %>
        <td><%= link_to 'Edit', edit_comment_path(comments) %></td>
        <td><%= link_to 'Destroy' %></td>
        <br>
      <% end %>


    </tr>
  <% end %>
  </tbody>
</table>

<%= link_to "Add new comment", new_comment_path(post_id: @post.id) %>